image: debian:buster-slim

stages:
  - build
  - deploy

build_website:
  stage: build
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
      - build/
  before_script:
    - apt update
    - apt install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_12.x | bash -
    - apt install -y python3 python3-pip pipenv make nodejs
  script:
    - pipenv install
    - make

deploy_to_test:
  stage: deploy
  dependencies:
    - build_website
  before_script:
    - apt update
    - apt install -c lftp
  script:
    - lftp -e "set ftp:ssl-allow no; mirror --parallel --no-symlinks -R build/ /" -u $TEST_FTP_USER,$TEST_FTP_PASS $TEST_FTP_HOST || true
  only:
    - test

deploy_to_live:
  stage: deploy
  dependencies:
    - build_website
  before_script:
    - apt update
    - apt install -c lftp
  script:
    - lftp -e "set ftp:ssl-allow no; mirror --parallel --no-symlinks -R build/ /" -u $LIVE_FTP_USER,$LIVE_FTP_PASS $LIVE_FTP_HOST || true
  only:
    - master
